### ISSUE TITLE
Plugin does not appear to be doing anything

### ISSUE THREAD

**Issue by RobertButera** [jupl/markdown-brunch#3]
Hi,

I've installed markdown-brunch as per the instructions.  I can see that the plugin has been installed, however when I do a brunch build the markdown file is not compiled.

Is there somewhere specific I need to put the file?

Where do the markdown files get compiled to? public/?

Do I need to make some change to config.coffee?

I have installed the plugin with the following entry in the dependencies section of plackage.json:

"markdown-brunch": ">= 1.0 < 1.6"

**Comment by jupl** [comment]
This plugin generates a template module in a fashion similar to other Brunch templates. It generates an HTML string that is wrapped in a module definition. (Before the string itself was wrapped in a function.) For example, let's say we have a file `app/templates/example.md` that contains:

``` markdown
# Header 1
```

If using the default Brunch settings then:

``` javascript
var template = require('template/example'); // "<h1>Header 1</h1>
```
